Repository alexweininger/game-state, pull requests merged in 2018-10, with the labels that each got.

#8 Initial commit of Daniel's branch and creation of 'toString' methods.
  .idea/misc.xml
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/Building.java
  app/src/main/java/cs/up/catan/catangamestate/City.java
  app/src/main/java/cs/up/catan/catangamestate/DevelopmentCards.java
  app/src/main/java/cs/up/catan/catangamestate/Dice.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/Knights.java
  app/src/main/java/cs/up/catan/catangamestate/MainActivity.java
  app/src/main/java/cs/up/catan/catangamestate/Player.java
  app/src/main/java/cs/up/catan/catangamestate/Road.java
  app/src/main/java/cs/up/catan/catangamestate/RoadBuilding.java
  app/src/main/java/cs/up/catan/catangamestate/Robber.java
  app/src/main/java/cs/up/catan/catangamestate/Settlement.java
  app/src/main/java/cs/up/catan/catangamestate/VictoryPoints.java
  app/src/main/java/cs/up/catan/catangamestate/YearofPlenty.java
Labels: enhancement

#12 Update README.md
  README.md
Labels: enhancement, hacktoberfest, todo

#14 Issue #11 Add UML diagrams
  .idea/runConfigurations.xml
  UML/Board.png
  UML/Building.png
  UML/City.png
  UML/DevelopmentCards.png
  UML/Dice.png
  UML/Game-State-All.png
  UML/GameState.png
  UML/Knights.png
  UML/MainActivity.png
  UML/Player.png
  UML/Road.png
  UML/RoadBuilding.png
  UML/Robber.png
  UML/Settlement.png
  UML/VictoryPoints.png
  UML/YearofPlenty.png
Labels: enhancement

#15 Updated 'onCreate' in MainActivity.
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: todo

#28 Alex
  .idea/misc.xml
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/Settlement.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, hacktoberfest, todo

#40 merge Alex board implementing
  .idea/misc.xml
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/Dice.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
Labels: enhancement, good first issue, hacktoberfest

#48 huge commit from alex
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/Building.java
  app/src/main/java/cs/up/catan/catangamestate/City.java
  app/src/main/java/cs/up/catan/catangamestate/DevelopmentCards.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/Knight.java
  app/src/main/java/cs/up/catan/catangamestate/Monopoly.java
  app/src/main/java/cs/up/catan/catangamestate/Player.java
  app/src/main/java/cs/up/catan/catangamestate/Road.java
  app/src/main/java/cs/up/catan/catangamestate/RoadDevCard.java
  app/src/main/java/cs/up/catan/catangamestate/Robber.java
  app/src/main/java/cs/up/catan/catangamestate/Settlement.java
  app/src/main/java/cs/up/catan/catangamestate/VictoryPoints.java
  app/src/main/java/cs/up/catan/catangamestate/YearOfPlenty.java
Labels: enhancement, hacktoberfest

#51 Alex - Board, Hexagon, GameState beginning to implement actions
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/DevelopmentCards.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/Hexagon.java
  app/src/main/java/cs/up/catan/catangamestate/Knight.java
  app/src/main/java/cs/up/catan/catangamestate/MainActivity.java
  app/src/main/java/cs/up/catan/catangamestate/Robber.java
Labels: enhancement, hacktoberfest

#91 GameState fixes, and starting to change Player resource data fixed #90
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/cs/up/catan/catangamestate/Board.java
  app/src/main/java/cs/up/catan/catangamestate/GameState.java
  app/src/main/java/cs/up/catan/catangamestate/Player.java
Labels: bug
